version: "3.8"

networks:
  rabbitexample:
    driver: bridge

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_app
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  producer:
    build: ./producer
    container_name: nodejs-producer
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5001:5001
    expose:
      - 5001
    volumes:
      - ./producer:/producer
    networks:
      - rabbitexample
    depends_on: 
      - rabbitmq
  
  consumer:
    build: ./consumer
    container_name: nodejs-consumer
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5002:5002
    expose:
      - 5002
    volumes:
      - ./consumer:/consumer
    networks:
      - rabbitexample
    depends_on: 
      - rabbitmq
